### ISSUE TITLE
Topic provisioning for producers ignores topic.properties settings

### ISSUE THREAD

**Issue by pzieminski** [spring-cloud/spring-cloud-stream-binder-kafka#684]
Using application configuration as follows

```
spring:
  cloud:
    stream:
      bindings:
        myoutput:
          destination: output-topic
        myinput:
          destination: input-topic
          group: mygroup

      kafka:
        streams:
          binder:
            brokers: docker-machine:9092
            autoCreateTopics: true
            minPartitionCount: 4
            configuration:
              state.dir: ${java.io.tmpdir}/kafka-streams
              commit.interval.ms: 3000
              producer.compression.type: snappy
              application.id: hello-world

          bindings:
            myoutput:
              producer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.topicprovisioningissue1.JsonNodeSerde
                topic.properties:
                  cleanup.policy: compact
            myinput:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.example.topicprovisioningissue1.JsonNodeSerde
                topic.properties:
                  cleanup.policy: compact
```
and bindings
```
public interface Bindings {

    String MYINPUT = "myinput";
    String MYOUTPUT = "myoutput";

    @Input(MYINPUT)
    KStream<String, JsonNode> input();

    @Output(MYOUTPUT)
    KStream<String, JsonNode> output();
}
```

Causes both topics output-topic and input-topic to be created, but only the consumer topic has its properties set (in this case cleanup.policy), while the producer properties are ignored.

I've debugged the binder code and the provisioning of topics for producers seems to always use empty properties. See `org.springframework.cloud.stream.binder.kafka.streams.KStreamBinder#doBindProducer`. `extendedProducerProperties` below are created in place and never populated with anything.
This is 2.1.2.RELEASE but 2.2.0.RELEASE looks the same.

```
	@Override
	@SuppressWarnings("unchecked")
	protected Binding<KStream<Object, Object>> doBindProducer(String name, KStream<Object, Object> outboundBindTarget,
															ExtendedProducerProperties<KafkaStreamsProducerProperties> properties) {
		ExtendedProducerProperties<KafkaProducerProperties> extendedProducerProperties = new ExtendedProducerProperties<>(
				new KafkaProducerProperties());
		this.kafkaTopicProvisioner.provisionProducerDestination(name, extendedProducerProperties);
		Serde<?> keySerde = this.keyValueSerdeResolver.getOuboundKeySerde(properties.getExtension());
		Serde<?> valueSerde = this.keyValueSerdeResolver.getOutboundValueSerde(properties, properties.getExtension());
		to(properties.isUseNativeEncoding(), name, outboundBindTarget, (Serde<Object>) keySerde, (Serde<Object>) valueSerde);
		return new DefaultBinding<>(name, null, outboundBindTarget, null);
	}
```

**Comment by pzieminski** [comment]
I've modified the original post and removed the `spring.cloud.stream.kafka.bindings` section - it's not necessary after all it turns out.

**Comment by sobychacko** [comment]
@pzieminski This issue is already resolved. Here is a [test](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/16bb3e2f62b4f1bb4ec1ffca62b214a23914300e) to verify. Can you please confirm? If you still see issues, please reopen this issue.

**Comment by pzieminski** [comment]
Hi, 
Using 
<spring-cloud.version>Greenwich.SR2</spring-cloud.version>
one type of topic still isn't provisioned with the configured topic properties set. Here is the configuration below. The value ignored is

spring.cloud.stream.kafka.streams.bindings.cdcDeletedOutput.producer.topic.properties.cleanup.policy

`
cms.streams:
  cdc:
    appId: cms-cdc
    group: cmsCdc
  search:
    appId: cms-search-sink
    group: cmsCdcSearchSink
  searchSender:
    appId: cms-search-sender
    group: cmsCdcSearchSender

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: docker-machine:9092
            autoCreateTopics: true
            minPartitionCount: 4
            configuration: # StreamsConfig
              state.dir: ${java.io.tmpdir}/kafka-streams
              commit.interval.ms: 5000
              producer:
                compression.type: snappy
              consumer:
                auto.offset.reset: earliest

---

spring.profiles: cdc

spring:
  cloud:
    stream:
      bindings:

        cdcInput:
          destination: postgres1.cms_all
          group: ${cms.streams.cdc.group}
          consumer:
            concurrency: 2
        cdcDeletedOutput:
          destination: ${cms.streams.cdc.appId}-deleted
          group: ${cms.streams.cdc.group}

      kafka:
        streams:
          bindings:
            cdcInput:
              consumer:
                applicationId: ${cms.streams.cdc.appId}
                keySerde: cdc.serializer.DefaultIdSerde
                valueSerde: cdc.serializer.EnvelopeSerde
                topic.properties:
                  cleanup.policy: delete
                  compression.type: snappy
                  retention.ms: -1
            cdcDeletedOutput:
              producer:
                keySerde: cms.cdc.serializer.DefaultIdSerde
                valueSerde: cdc.serializer.PayloadAggregateSerde
                compressionType: snappy
                topic.properties.cleanup.policy: compact
`

**Comment by sobychacko** [comment]
@pzieminski I think you are missing the `log` part in the configuration. `spring.cloud.stream.kafka.streams.bindings.cdcDeletedOutput.producer.topic.properties.log.cleanup.policy`.

**Comment by pzieminski** [comment]
I tried it with 
`spring.cloud.stream.kafka.streams.bindings.cdcDeletedOutput.producer.topic.properties.log.cleanup.policy`
without success. Consumer works thought without `.log.`

I don't see anything about this in the documentation
https://cloud.spring.io/spring-cloud-static/Greenwich.SR2/multi/multi__apache_kafka_streams_binder.html

**Comment by sobychacko** [comment]
@pzieminski My bad. It is indeed `spring.cloud.stream.kafka.streams.bindings.cdcDeletedOutput.producer.topic.properties.cleanup.policy`.
I am not able to reproduce what you are seeing with `Greenwich.SR2`. Here is a [sample app](https://github.com/schacko-samples/kafka-binder-gh-684) I just put together based on your bindings. When I debug to the `doBindProduer` method in `KStreamBinder`, I am seeing the topic level `cleanup.policy` there. What am I doing differently from what you are trying to do?

In the meantime, I re-opened this issue. We should improve the docs with more details.

**Comment by pzieminski** [comment]
@sobychacko Thank you for setting it up the sample. I got the app locally, built it, pointed it to my local kafka node, I started it up and two topic were created `input-topic` and `output-topic`. Here is what I see for both of them. As you can see, the `output-topic` created with the producer configuration doesn't have its cleanup policy set.

```
D:\kafka>c:\Tools\kafka_2.12-2.3.0\bin\windows\kafka-topics.bat --zookeeper docker-machine:2181 --describe --topic output-topic
Topic:output-topic      PartitionCount:1        ReplicationFactor:1     Configs:
        Topic: output-topic     Partition: 0    Leader: 1       Replicas: 1     Isr: 1

D:\kafka>c:\Tools\kafka_2.12-2.3.0\bin\windows\kafka-topics.bat --zookeeper docker-machine:2181 --describe --topic input-topic
Topic:input-topic       PartitionCount:1        ReplicationFactor:1     Configs:cleanup.policy=compact
        Topic: input-topic      Partition: 0    Leader: 1       Replicas: 1     Isr: 1
```

I used these two docker images
https://hub.docker.com/r/debezium/zookeeper
https://hub.docker.com/r/debezium/kafka

**Comment by sobychacko** [comment]
@pzieminski I misunderstood the problem and I agree that there is a bug. My apologies. The correct extended properties object is passed to the `doBindProducer` method, but it is then overridden by a new object. I corrected the issue and applied a fix [upstream](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/39a5b25b9cc3a3c4e6af2c235cb50a4d1064edab). The same change is backported to both 2.2.x and 2.1.x branches. The docs already mention right properties both in the consumer and producer sections and therefore I didn't update any docs. 

Please feel free to re-open this issue if you still see issues. 

Thank you!

**Comment by kucukil** [comment]
@sobychacko @pzieminski It seems it is not fixed. Because the partitionCount given with bindings does not override min-partition-count given under binder prop.

My application.yml is below;

`spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            auto-add-partitions: true
            min-partition-count: 4
            configuration:
              commit.interval.ms: 1000
          bindings:
            input:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
            output:
              producer:
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        input:
          destination: ad-bidding-impressions
        output:
          destination: ad-impressions-output
          producer:
            partitionKeyExpression: payload.sellerId
            partitionCount: 10`
