### ISSUE TITLE
IllegalArgumentException: Unknown type for contentType header value: class [B

### ISSUE THREAD

**Issue by santhoshpt** [spring-cloud/spring-cloud-stream-binder-kafka#863]
It was working fine with spring boot 2.1.11 and I'm facing this issue after upgrading to 2.2.5. I'm using the following dependencies in my build.gradle. Is the following schema dependency is correct? I'm using the content-type as "application/*+avro" with schema registry.

**Dependencies after upgrade**
org.springframework.boot:spring-boot-dependencie:2.2.5
org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR3
org.springframework.cloud:spring-cloud-stream-dependencies:Horsham.SR3
org.springframework.cloud:spring-cloud-stream-schema:2.2.1.RELEASE

**Dependencies before upgrade**
org.springframework.boot:spring-boot-dependencie:2.2.11
org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2
org.springframework.cloud:spring-cloud-stream-dependencies:Fishtown.SR3
org.springframework.cloud:spring-cloud-stream-schema:2.1.0.RELEASE
org.springframework.cloud:spring-cloud-stream-binder-kafka:2.1.0.RELEAS

**Getting the following exception after upgrade**
```
Caused by: java.lang.IllegalArgumentException: Unknown type for contentType header value: class [B at org.springframework.messaging.converter.DefaultContentTypeResolver.resolve(DefaultContentTypeResolver.java:76)
at org.springframework.messaging.converter.AbstractMessageConverter.getMimeType(AbstractMessageConverter.java:265)
at org.springframework.messaging.converter.AbstractMessageConverter.supportsMimeType(AbstractMessageConverter.java:251)
at org.springframework.cloud.stream.schema.avro.AvroSchemaRegistryClientMessageConverter.supportsMimeType(AvroSchemaRegistryClientMessageConverter.java:285)
at org.springframework.messaging.converter.AbstractMessageConverter.canConvertFrom(AbstractMessageConverter.java:201)
at org.springframework.cloud.stream.schema.avro.AbstractAvroMessageConverter.canConvertFrom(AbstractAvroMessageConverter.java:84)
at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:194)
at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70)
```

**Comment by santhoshpt** [comment]
I'm getting this issue because of older version of kafka producer and new version of kafka consumer.  As part of my upgrading the kafka client versions there were some messages existed in the kafka topic which are produced by older kafka binder version.

**Comment by johan1a** [comment]
Did you get it to work with the versions under 'Dependencies after upgrade" in the end? I am having the same problem.

**Comment by olegz** [comment]
Guys, the issue was fixed https://github.com/spring-cloud/spring-cloud-stream/issues/1902 in Horsham.SR2 which is pulled by s-c-cloud Hoxton.SR2. It is not available in Greenwich.

**Comment by sobychacko** [comment]
@olegz As discussed, I am reopening this issue as we found out that this is still a problem with non-json converters.

**Comment by sobychacko** [comment]
Here is the core issue: https://github.com/spring-cloud/spring-cloud-stream/issues/1941

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-stream/commit/81755865c8b5c172104a61261d6d940d25b7eecd.
